name: .NET Core

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: create folder
        run: mkdir app
      - name: Build
        run: dotnet publish -o app -r win-x64 -p:PublishSingleFile=true --self-contained true
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: will it workkkk
          path: app
